### ISSUE TITLE
Broken Counter

### ISSUE THREAD

**Issue by VFXGamer** [nayanmapara/PhishBuster#4]
I am not sure why the counter is not working.

![counter](https://user-images.githubusercontent.com/62838631/135715964-7a952e28-0f48-454c-afdc-393cf3c6acbd.jpg)
 
It would be great if I can get the PR with the fix otherwise just the solution on how can I fix it would also be really appreciated.

**Comment by Siddharth1002** [comment]
Can I try working on this issue?

**Comment by VFXGamer** [comment]
Yea give it a shot. I am not sure what is causing the issue you will have to debug the code.

**Comment by preeti-14-7** [comment]
Can i fix this ?

**Comment by VFXGamer** [comment]
Yea sure go ahead.

**Comment by preeti-14-7** [comment]
assign this to me

**Comment by ainneo** [comment]
I want to work on this!

**Comment by VFXGamer** [comment]
I will add you yo assignees.

**Comment by preeti-14-7** [comment]
How to set it locally ?
